name: Renovate Snapshot Update

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "values.yaml"

permissions:
  contents: write
  packages: read

jobs:
  update-snapshots:
    uses: orhayoun-eevee/build-workflow/.github/workflows/renovate-snapshot-update.yaml@b950e7ca269da7fc0fa2f6ef92cdcc5890bb0e31
    with:
      build_workflow_ref: b950e7ca269da7fc0fa2f6ef92cdcc5890bb0e31
      snapshots_dir: tests/snapshots
    secrets:
      gh_app_id: ${{ secrets.GHCR_AUTO_APP_ID }}
      gh_app_private_key: ${{ secrets.GHCR_AUTO_PKEY }}
