name: Validate Renovate Config

on:
  pull_request:
    paths:
      - 'renovate.json'
      - 'renovate.json5'
      - '.github/renovate.json'
      - '.github/renovate.json5'
      - '.github/workflows/renovate-config.yaml'
  push:
    branches:
      - main
    paths:
      - 'renovate.json'
      - 'renovate.json5'
      - '.github/renovate.json'
      - '.github/renovate.json5'
      - '.github/workflows/renovate-config.yaml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Validate renovate config
        run: |
          docker run --rm -v "$PWD:/repo" -w /repo ghcr.io/renovatebot/renovate:latest renovate-config-validator
          docker run --rm -v "$PWD:/repo" -w /repo ghcr.io/renovatebot/renovate:latest renovate-config-validator --strict
