name: Validate Renovate Config

on:
  pull_request:
    paths:
      - 'renovate.json'
      - 'renovate.json5'
      - '.github/renovate.json'
      - '.github/renovate.json5'
      - '.github/workflows/renovate-config.yaml'
  push:
    branches:
      - main
    paths:
      - 'renovate.json'
      - 'renovate.json5'
      - '.github/renovate.json'
      - '.github/renovate.json5'
      - '.github/workflows/renovate-config.yaml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    uses: orhayoun-eevee/build-workflow/.github/workflows/renovate-config.yaml@v0.1.5
