name: Renovate Snapshot Update

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "values.yaml"

permissions:
  contents: write
  packages: read

concurrency:
  group: renovate-snapshot-update-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-snapshots:
    if: github.event.pull_request.head.repo.full_name == github.repository
    timeout-minutes: 30
    uses: orhayoun-eevee/build-workflow/.github/workflows/renovate-snapshot-update.yaml@v0.1.12
    with:
      snapshots_dir: tests/snapshots
    secrets:
      gh_app_id: ${{ secrets.GHCR_AUTO_APP_ID }}
      gh_app_private_key: ${{ secrets.GHCR_AUTO_PKEY }}
